CREATE TABLE state(
	id BIGINT AUTO_INCREMENT,
	name VARCHAR(200) UNIQUE NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE city(
	id BIGINT AUTO_INCREMENT,
	name VARCHAR(200) UNIQUE NOT NULL,
	state BIGINT,
	PRIMARY KEY(id),
	FOREIGN KEY (state) REFERENCES state(id)
);